const ChoreyApp=(()=>{
 const {getPerson,escapeHTML}=ChoreyUtils,{profileRepository,taskRepository,occurrenceRepository,dailyRepository}=ChoreyRepositories;
 let activeDayData=null,currentTasks=[],currentStates={},currentView="today",refreshing=false,congrats=false;const POLL=60000;
 async function active(){return getPerson(await profileRepository.getActivePersonId())}
 function banner(msg){document.querySelector('.connection-banner')?.remove();if(!msg)return;const b=document.createElement('div');b.className='connection-banner';b.innerHTML=`<span>${escapeHTML(msg)}</span><button class="connection-retry">Retry</button>`;document.querySelector('.container')?.prepend(b);b.querySelector('button').onclick=()=>init()}
 async function loadTasks(){let t=await taskRepository.getAll();if(!t.length){await taskRepository.seedDefaults(defaultTasks);t=await taskRepository.getAll()}return t}
 function defaultState(task){return ChoreyTaskModel.normalizeOccurrence({assignedIds:task.defaultAssignedIds||[],selfAssignedIds:[],isDone:false},task)}
 function visibleOccurrences(day,states){return day.occurrences.filter(item=>!(item.occurrence.duration==='indefinite'&&states[item.id]?.isDone&&states[item.id]?.completedAt?.slice(0,10)!==day.dateKey))}
 async function init({background=false}={}){if(refreshing)return;refreshing=true;try{const person=await active();const tasks=await loadTasks();const day=ChoreyScheduler.buildDayData(tasks,person,ChoreyClock.now());const states=await occurrenceRepository.getAll(tasks);currentTasks=tasks;currentStates=states;activeDayData={...day,occurrences:visibleOccurrences(day,states)};await dailyRepository.prepare(day.dateKey);congrats=await dailyRepository.getCongratulationsShown();banner();ChoreyUI.updateHeader(person,()=>ChoreyTaskCreator.open(person,refresh),{title:currentView==='all'?'All Tasks':undefined});if(!person){currentView='today';renderLogin();return}if(currentView==='all')renderAll(person);else renderToday(person)}catch(e){console.error(e);banner('Shared chores are unavailable. Check the connection and try again.');if(!background&&!document.getElementById('app-viewport').innerHTML.trim())document.getElementById('app-viewport').innerHTML='<div class="connection-empty">Shared chores unavailable</div>'}finally{refreshing=false}}
 async function refresh(){await init({background:true})}
 function renderLogin(){ChoreyUI.renderLoginScreen(async id=>{const p=getPerson(id),code=prompt(`Enter passcode for ${p.name}:`);if(code===p.passcode){await profileRepository.setActivePersonId(id);await init()}else if(code!==null)alert('Incorrect profile passcode.')})}
 function occurrenceItem(item){return {...item,...defaultState(item.task),...(currentStates[item.id]||{})}}
 function buildSections(person){const sections=new Map([['unassigned',[]],...people.map(p=>[p.id,[]])]);activeDayData.occurrences.forEach(item=>{const configured=occurrenceItem(item),ids=configured.assignedIds||[];if(!ids.length)sections.get('unassigned').push(configured);else ids.forEach(id=>sections.get(id)?.push(configured))});return sections}
 function bindRows(person){const v=document.getElementById('app-viewport');v.querySelectorAll('.chore-item[data-id]').forEach(row=>{const id=row.dataset.id,button=row.querySelector('.assignment-button');if(button)button.addEventListener('click',e=>{e.stopPropagation();manageAssignment(id,person)});const c=row.querySelector('.chore-checkbox');c?.addEventListener('click',e=>e.stopPropagation());c?.addEventListener('change',async e=>{const wanted=e.target.checked;try{if(!await toggle(id,wanted,person))e.target.checked=!wanted}catch(err){e.target.checked=!wanted;banner('The completion was not changed.')}})});v.querySelectorAll('.swipe-row.can-edit').forEach(w=>ChoreySwipe.enableAction(w,{onAction:()=>editTask(w.dataset.taskId,person)}));v.querySelector('#view-all-tasks')?.addEventListener('click',()=>{currentView='all';init()})}
 async function renderToday(person){const sections=buildSections(person);const due=activeDayData.occurrences.filter(i=>i.occurrence.duration==='day'||i.occurrence.closesOn===activeDayData.dateKey);if(due.length&&due.every(i=>currentStates[i.id]?.isDone)&&!congrats){congrats=true;await dailyRepository.setCongratulationsShown(true);ChoreyUI.showCongratulations()}document.getElementById('date-subheading').textContent=activeDayData.displayDate;ChoreySwipe.resetOpenRow();const v=document.getElementById('app-viewport');if(!activeDayData.occurrences.length)ChoreyUI.renderEmptyDay(person);else v.innerHTML=ChoreyUI.renderBoard(person,activeDayData,sections);bindRows(person)}
 function renderAll(person){document.getElementById('date-subheading').textContent='Task Library';const v=document.getElementById('app-viewport');v.innerHTML=ChoreyUI.renderAllTasks(currentTasks,person);v.querySelectorAll('.swipe-row.can-edit').forEach(w=>ChoreySwipe.enableAction(w,{onAction:()=>editTask(w.dataset.taskId,person)}));v.querySelector('#back-to-today').onclick=()=>{currentView='today';init()}}
 async function editTask(id,person){const task=currentTasks.find(t=>t.id===id);if(task&&ChoreyTaskModel.canEditTask(person,task))await ChoreyTaskCreator.open(person,refresh,task)}
 async function manageAssignment(id,person){const item=activeDayData.occurrences.find(i=>i.id===id);if(!item||item.task.visibility==='private')return;const state=currentStates[id]||defaultState(item.task);if(!ChoreyTaskModel.canManageAssignments(person)){if(!state.assignedIds.length){state.assignedIds=[person.id];state.selfAssignedIds=[person.id];state.assignedById=person.id;state.assignmentType='temporary';await occurrenceRepository.set(id,state,item.task)}else if(state.selfAssignedIds?.includes(person.id)){await occurrenceRepository.delete(id)}else return;return refresh()}
 openAssignmentModal(item,state,person)}
 function openAssignmentModal(item,state,person){const o=document.createElement('div');o.className='assignment-overlay';let shared=false,selected=new Set(state.assignedIds||[]);const assignable=people;let holdTimer=null,held=false;
 function holdAction(element,action){element.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;held=false;holdTimer=setTimeout(()=>{held=true;action(true);navigator.vibrate?.(25)},700)});['pointerup','pointercancel','pointerleave'].forEach(type=>element.addEventListener(type,()=>clearTimeout(holdTimer)));element.addEventListener('click',e=>{e.stopPropagation();if(!held)action(false);held=false})}
 function draw(){const enough=selected.size>1;o.innerHTML=`<div class="assignment-modal-card"><div class="assignment-modal-title">Assign Task</div><ul class="chore-list">${assignable.map(p=>`<li class="chore-item profile-card${selected.has(p.id)?' current-selection':''}" data-person="${p.id}" style="--person-accent:${p.accent}"><span class="chore-title">${escapeHTML(p.name)}</span></li>`).join('')}</ul><button class="secondary-button" data-unassign>Unassigned</button><button class="modal-cancel">Cancel</button><button class="shared-task-button${shared?' selected':''}" data-confirm ${shared&&!enough?'disabled':''}>${shared?'Confirm':'Shared Task'}</button></div>`;
 o.querySelectorAll('[data-person]').forEach(r=>{if(shared)r.addEventListener('click',()=>{selected.has(r.dataset.person)?selected.delete(r.dataset.person):selected.add(r.dataset.person);draw()});else holdAction(r,permanent=>apply([r.dataset.person],permanent))});
 const confirm=o.querySelector('[data-confirm]');if(!shared)confirm.onclick=()=>{shared=true;selected.clear();draw()};else if(!confirm.disabled)holdAction(confirm,permanent=>apply([...selected],permanent));holdAction(o.querySelector('[data-unassign]'),permanent=>apply([],permanent));o.querySelector('.modal-cancel').onclick=()=>o.remove()}
 async function apply(ids,permanent){try{if(permanent){const task={...item.task,defaultAssignedIds:ids};await taskRepository.update(task);await occurrenceRepository.delete(item.id)}else{const next={...state,assignedIds:ids,selfAssignedIds:[],assignedById:person.id,assignmentType:'temporary',isDone:false,completedById:null,completedAt:null};ids.length?await occurrenceRepository.set(item.id,next,item.task):await occurrenceRepository.delete(item.id)}o.remove();await refresh()}catch(e){console.error(e);banner('The assignment was not changed.')}}document.body.appendChild(o);draw()}
 async function toggle(id,checked,person){const item=activeDayData.occurrences.find(i=>i.id===id);if(!item)return false;const state=currentStates[id]||defaultState(item.task),assigned=state.assignedIds||[];if(checked){if(assigned.length&&!assigned.includes(person.id)&&!person.isOwner&&!person.isAdmin)return false;const next={...state,isDone:true,completedById:person.id,completedAt:new Date().toISOString()};if(!assigned.length&&item.task.visibility!=='private'){next.assignedIds=[person.id];next.selfAssignedIds=[person.id];next.assignedById=person.id;next.assignmentType='temporary'}await occurrenceRepository.set(id,next,item.task)}else{const worker=getPerson(state.completedById);if(!(state.completedById===person.id||person.isOwner||(person.isAdmin&&!worker?.isOwner)))return false;const next={...state,isDone:false,completedById:null,completedAt:null};await occurrenceRepository.set(id,next,item.task);congrats=false;await dailyRepository.setCongratulationsShown(false)}await refresh();return true}
 const date=document.getElementById('date-subheading');let hold,dateHeld=false;
 function openDeveloperMenu(){document.querySelector('.developer-overlay')?.remove();const overlay=document.createElement('div');overlay.className='developer-overlay';const simulated=ChoreyClock.now().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'});overlay.innerHTML=`<div class="developer-modal-card" role="dialog" aria-modal="true" aria-label="Developer menu"><div class="developer-modal-title">Developer</div><div class="developer-version">Chorey v${escapeHTML(CHOREY_APP_VERSION)}</div><div class="developer-date-status">Scheduler date: ${escapeHTML(simulated)}</div><button class="developer-menu-button danger" data-dev-action="reset-shared">Reset Default Task List</button><button class="developer-menu-button danger" data-dev-action="reset-local">Reset Local Data</button><div class="developer-menu-label">Time Travel</div><button class="developer-menu-button" data-dev-action="tomorrow">Tomorrow</button><button class="developer-menu-button" data-dev-action="week">Next Week</button><button class="developer-menu-button" data-dev-action="month">Next Month</button><button class="developer-menu-button" data-dev-action="today" ${ChoreyClock.isOverridden()?'':'disabled'}>Return to Today</button><button class="developer-menu-button cancel" data-dev-action="cancel">Cancel</button></div>`;document.body.appendChild(overlay);overlay.onclick=async e=>{const action=e.target.closest('[data-dev-action]')?.dataset.devAction;if(!action){if(e.target===overlay)overlay.remove();return}if(action==='cancel'){overlay.remove();return}if(action==='reset-local'){if(!confirm("Reset this device's local Chorey settings? Shared tasks and completions will not be changed."))return;ChoreyStorage.resetAllData();location.reload();return}if(action==='reset-shared'){const owner=await active();if(!owner?.isOwner)return;const passcode=prompt('Enter the Owner passcode to reset the shared task list:');if(passcode===null)return;if(passcode!==owner.passcode){alert('Incorrect Owner passcode.');return}if(!confirm('Reset the shared task list to the current hardcoded defaults? This permanently deletes every shared task, assignment, and completion.'))return;await taskRepository.resetToDefaults(defaultTasks);overlay.remove();currentView='today';await init();return}if(action==='tomorrow')ChoreyClock.advanceDays(1);if(action==='week')ChoreyClock.advanceDays(7);if(action==='month')ChoreyClock.advanceMonth();if(action==='today')ChoreyClock.returnToToday();overlay.remove();currentView='today';await init()}}
 date.addEventListener('pointerdown',()=>{dateHeld=false;hold=setTimeout(async()=>{const p=await active();if(!p?.isOwner)return;dateHeld=true;openDeveloperMenu()},1000)});['pointerup','pointerleave','pointercancel'].forEach(x=>date.addEventListener(x,()=>clearTimeout(hold)));date.addEventListener('click',async e=>{if(dateHeld){e.preventDefault();dateHeld=false;return}currentView='today';await profileRepository.clearActivePerson();await init()});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!document.querySelector('.assignment-overlay'))init({background:true})});window.addEventListener('focus',()=>init({background:true}));setInterval(()=>{if(!document.hidden&&!document.querySelector('.assignment-overlay'))init({background:true})},POLL);
 return Object.freeze({init});})();
ChoreyApp.init();
