const ChoreyTaskCreator=(()=>{
 const {daysOfWeek,monthsOfYear,escapeHTML,dateKey}=ChoreyUtils,{taskRepository}=ChoreyRepositories,clone=v=>JSON.parse(JSON.stringify(v));
 const weekOptions=[[1,"First week"],[2,"Second week"],[3,"Third week"],[4,"Fourth week"],[5,"Fifth week"],["last","Last week"]];
 const ordinalOptions=[[1,"First"],[2,"Second"],[3,"Third"],[4,"Fourth"],["last","Last"]];
 async function open(actor,onSaved,existingTask=null){
  if(!actor)return;const editing=!!existingTask;if(editing&&!ChoreyTaskModel.canEditTask(actor,existingTask))return;
  const original=existingTask?ChoreyTaskModel.normalizeTask(existingTask):null,s=original?.schedule;
  const draft=original?{name:original.name,category:original.category,type:s.type,repeats:s.repeats,days:[...s.days],weeks:[...s.weeks],months:[...s.months],oneTimeKeys:[...s.oneTimeKeys],dateRule:s.dateRule?clone(s.dateRule):null,seasonal:["days","weeks"].includes(s.type)&&!!s.months.length,visibility:original.visibility}:{name:"",category:"General",type:null,repeats:true,days:[],weeks:[],months:[],oneTimeKeys:[],dateRule:null,seasonal:false,visibility:"visible"};
  const overlay=document.createElement("div");overlay.className="assignment-overlay";document.body.appendChild(overlay);
  const show=h=>overlay.innerHTML=`<div class="assignment-modal-card task-creator">${h}</div>`,cancel=()=>'<button class="modal-cancel modal-control" data-cancel>Cancel</button>',bind=()=>{overlay.querySelector("[data-cancel]")?.addEventListener("click",()=>overlay.remove());bindDelete()},sel=x=>x?" current-selection":"";
  const checkRow=(value,label,checked,extra="")=>`<label class="selector-check chore-style-option${sel(checked)}" ${extra}><input class="chore-checkbox" type="checkbox" value="${value}" ${checked?"checked":""}><span class="chore-title">${label}</span></label>`;
  const repeatButton=()=>draft.type==="anytime"?"":`<button class="repeat-toggle modal-control${draft.repeats?" selected":""}" type="button" data-repeat>${draft.repeats?"Repeats":"One Time"}</button>`;
  function bindRepeat(reopen){const b=overlay.querySelector("[data-repeat]");if(b)b.onclick=()=>{draft.repeats=!draft.repeats;draft.oneTimeKeys=[];reopen()}}
  function name(){show(`<div class="assignment-modal-title">${editing?"Edit Task":"New Task"}</div><form class="modal-form" id="task-name-form"><label class="field-label">Name<input class="text-input modal-control task-name-input" id="task-name" maxlength="80" value="${escapeHTML(draft.name)}" autofocus></label><button class="primary-button modal-control" type="submit">Continue</button></form>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#task-name-form").addEventListener("submit",e=>{e.preventDefault();draft.name=overlay.querySelector("#task-name").value.trim();if(!draft.name)return alert("Enter a task name.");category()})}
  async function categories(){const m=new Map(),add=v=>{v=String(v||"").trim();if(v&&!m.has(v.toLowerCase()))m.set(v.toLowerCase(),v)};defaultTasks.forEach(t=>add(t.category));(await taskRepository.getAll()).forEach(t=>add(t.category));return [...m.values()].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:"base"}))}
  async function category(){const list=await categories();show(`<div class="assignment-modal-title">Choose a category</div><ul class="chore-list category-selector-list">${list.map(c=>`<li class="chore-item selector-row${sel(c===draft.category)}" style="--category-accent:${ChoreyUI.categoryColor(c)}" data-category="${escapeHTML(c)}"><span class="chore-title">${escapeHTML(c)}</span></li>`).join("")}<li class="chore-item selector-row" data-new-category><span class="chore-title">Add new category</span></li></ul>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll("[data-category]").forEach(r=>r.onclick=()=>{draft.category=r.dataset.category;type()});overlay.querySelector("[data-new-category]").onclick=newCategory}
  function newCategory(){show(`<div class="assignment-modal-title">New category</div><form class="modal-form" id="category-form"><label class="field-label">Category name<input class="text-input modal-control" id="new-category" maxlength="40" autofocus></label><button class="primary-button modal-control" type="submit">Accept</button></form>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#category-form").onsubmit=async e=>{e.preventDefault();const c=overlay.querySelector("#new-category").value.trim();if(!c)return alert("Enter a category name.");draft.category=(await categories()).find(x=>x.localeCompare(c,undefined,{sensitivity:"base"})===0)||c;type()}}
  function type(){const choices=[["days","Days"],["weeks","Weeks"],["months","Months"],["dates","Dates"],["anytime","Anytime"]];show(`<div class="assignment-modal-title">Occurs on these…</div><ul class="chore-list">${choices.map(([v,l])=>`<li class="chore-item selector-row${sel(draft.type===v)}" data-type="${v}"><span class="chore-title">${l}</span></li>`).join("")}</ul>${cancel()}${!editing?`<button class="private-task-button modal-control${draft.visibility==="private"?" selected":""}" type="button" data-private>Private Task 🔒</button>`:""}${editing?del():""}`);bind();const p=overlay.querySelector("[data-private]");if(p)p.onclick=()=>{draft.visibility=draft.visibility==="private"?"visible":"private";type()};overlay.querySelectorAll("[data-type]").forEach(r=>r.onclick=()=>{draft.type=r.dataset.type;if(draft.type==="anytime"){draft.repeats=false;save()}else if(draft.type==="days")days();else if(draft.type==="weeks")weeks();else if(draft.type==="months")months(false);else dates()})}
  function days(){show(`<div class="assignment-modal-title">Choose days</div><div class="selector-list">${daysOfWeek.map((d,i)=>checkRow(i,d,draft.days.includes(i))).join("")}${checkRow("seasonal","Seasonal",draft.seasonal,'class="seasonal-row"')}</div>${repeatButton()}<button class="primary-button modal-control" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();bindRepeat(days);overlay.querySelector("#accept").onclick=()=>{draft.days=[...overlay.querySelectorAll('.selector-check input:checked')].filter(i=>i.value!=="seasonal").map(i=>+i.value);draft.seasonal=overlay.querySelector('input[value="seasonal"]').checked;if(!draft.days.length)return alert("Choose at least one day.");draft.seasonal?months(true):finishSchedule()}}
  function weeks(){show(`<div class="assignment-modal-title">Choose weeks</div><div class="selector-list">${weekOptions.map(([v,l])=>checkRow(v,l,draft.weeks.map(String).includes(String(v)))).join("")}${checkRow("seasonal","Seasonal",draft.seasonal)}</div>${repeatButton()}<button class="primary-button modal-control" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();bindRepeat(weeks);overlay.querySelector("#accept").onclick=()=>{draft.weeks=[...overlay.querySelectorAll('.selector-check input:checked')].filter(i=>i.value!=="seasonal").map(i=>i.value==="last"?"last":+i.value);draft.seasonal=overlay.querySelector('input[value="seasonal"]').checked;if(!draft.weeks.length)return alert("Choose at least one week.");draft.seasonal?months(true):finishSchedule()}}
  function months(seasonal){show(`<div class="assignment-modal-title">${seasonal?"Choose active months":"Choose months"}</div><div class="selector-list">${monthsOfYear.map((m,i)=>checkRow(i+1,m,draft.months.includes(i+1))).join("")}</div>${seasonal?"":repeatButton()}<button class="primary-button modal-control" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();if(!seasonal)bindRepeat(()=>months(false));overlay.querySelector("#accept").onclick=()=>{draft.months=[...overlay.querySelectorAll('.selector-check input:checked')].map(i=>+i.value);if(!draft.months.length)return alert("Choose at least one month.");finishSchedule()}}
  function dates(){show(`<div class="assignment-modal-title">Choose dates</div><ul class="chore-list"><li class="chore-item selector-row" data-date-mode="specific"><span class="chore-title">Specific Date</span></li><li class="chore-item selector-row" data-date-mode="pattern"><span class="chore-title">Date Pattern</span></li></ul>${repeatButton()}${cancel()}${editing?del():""}`);bind();bindRepeat(dates);overlay.querySelector('[data-date-mode="specific"]').onclick=specificDate;overlay.querySelector('[data-date-mode="pattern"]').onclick=patternOrdinal}
  function picker(title,options,current,onPick){show(`<div class="assignment-modal-title">${title}</div><ul class="chore-list selector-scroll">${options.map(([v,l])=>`<li class="chore-item selector-row${sel(String(v)===String(current))}" data-value="${v}"><span class="chore-title">${l}</span></li>`).join("")}</ul>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll('[data-value]').forEach(row=>row.onclick=()=>onPick(row.dataset.value))}
  function specificDate(){const now=ChoreyClock.now(),rule=draft.dateRule?.kind==="specific"?draft.dateRule:{kind:"specific",month:now.getMonth()+1,day:now.getDate(),year:now.getFullYear()};draft.dateRule=rule;picker("Choose month",monthsOfYear.map((m,i)=>[i+1,m]),rule.month,v=>{rule.month=+v;specificDay()})}
  function specificDay(){const r=draft.dateRule,max=new Date(r.year||ChoreyClock.now().getFullYear(),r.month,0).getDate();picker("Choose day",Array.from({length:max},(_,i)=>[i+1,String(i+1)]),r.day,v=>{r.day=+v;draft.repeats?specificSummary():specificYear()})}
  function specificYear(){const y=ChoreyClock.now().getFullYear();picker("Choose year",Array.from({length:8},(_,i)=>[y+i,String(y+i)]),draft.dateRule.year||y,v=>{draft.dateRule.year=+v;specificSummary()})}
  function specificSummary(){const r=draft.dateRule,label=`${monthsOfYear[r.month-1]} ${r.day}${draft.repeats?"":`, ${r.year}`}`;show(`<div class="assignment-modal-title">Specific Date</div><div class="chore-item schedule-summary"><span class="chore-title">${label}</span></div>${repeatButton()}<button class="primary-button modal-control" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();bindRepeat(()=>{if(!draft.repeats&&!r.year)r.year=ChoreyClock.now().getFullYear();specificSummary()});overlay.querySelector("#accept").onclick=finishSchedule}
  function patternOrdinal(){const r=draft.dateRule?.kind==="pattern"?draft.dateRule:{kind:"pattern",ordinal:2,weekday:5,months:[]};draft.dateRule=r;picker("Choose pattern",ordinalOptions,r.ordinal,v=>{r.ordinal=v==="last"?"last":+v;patternWeekday()})}
  function patternWeekday(){const r=draft.dateRule;picker("Choose weekday",daysOfWeek.map((d,i)=>[i,d]),r.weekday,v=>{r.weekday=+v;patternMonths()})}
  function patternMonths(){const r=draft.dateRule;show(`<div class="assignment-modal-title">Choose active months</div><div class="selector-list">${monthsOfYear.map((m,i)=>checkRow(i+1,m,!r.months.length||r.months.includes(i+1))).join("")}</div>${repeatButton()}<button class="primary-button modal-control" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();bindRepeat(patternMonths);overlay.querySelector("#accept").onclick=()=>{r.months=[...overlay.querySelectorAll('.selector-check input:checked')].map(i=>+i.value);if(!r.months.length)return alert("Choose at least one month.");finishSchedule()}}
  function nextKeys(){const now=new Date(ChoreyClock.now());now.setHours(12,0,0,0);const keys=[];
   if(draft.type==="days")for(let offset=0;offset<400&&keys.length<draft.days.length;offset++){const d=new Date(now);d.setDate(now.getDate()+offset);if(draft.days.includes(d.getDay())&&(!draft.months.length||draft.months.includes(d.getMonth()+1)))keys.push(dateKey(d))}
   if(draft.type==="weeks")for(let offset=0;offset<430;offset++){const d=new Date(now);d.setDate(now.getDate()+offset);const info=ChoreyScheduler.getWeekInfo(d),anchor=dateKey(info.saturday),match=draft.weeks.some(w=>w==="last"?info.isLast:Number(w)===info.weekNumber)&&(!draft.months.length||draft.months.includes(info.saturday.getMonth()+1));if(match&&!keys.includes(anchor))keys.push(anchor);if(keys.length>=draft.weeks.length*Math.max(1,draft.months.length||1))break}
   if(draft.type==="months")draft.months.forEach(month=>{let year=now.getFullYear();if(month<now.getMonth()+1)year++;keys.push(`${year}-${String(month).padStart(2,"0")}`)});
   if(draft.type==="dates"){for(let offset=0;offset<800;offset++){const d=new Date(now);d.setDate(now.getDate()+offset);const r=draft.dateRule;let match=r.kind==="specific"?d.getMonth()+1===r.month&&d.getDate()===r.day&&(!r.year||d.getFullYear()===r.year):d.getDay()===r.weekday&&(!r.months.length||r.months.includes(d.getMonth()+1))&&((r.ordinal==="last"&&new Date(d.getFullYear(),d.getMonth(),d.getDate()+7).getMonth()!==d.getMonth())||Number(r.ordinal)===Math.floor((d.getDate()-1)/7)+1);if(match){keys.push(dateKey(d));if(r.kind==="specific"||keys.length>=Math.max(1,r.months?.length||1))break}}}
   return [...new Set(keys)];
  }
  function finishSchedule(){draft.oneTimeKeys=draft.repeats?[]:nextKeys();if(!draft.repeats&&!draft.oneTimeKeys.length)return alert("No upcoming occurrence matches that schedule.");save()}
  function del(){return '<button class="hold-delete-button modal-control" type="button" data-hold-delete><span class="hold-delete-progress"></span><span class="hold-delete-label">Hold to Permanently Delete</span></button>'}
  function bindDelete(){const b=overlay.querySelector("[data-hold-delete]");if(!b||!editing)return;let t;const stop=()=>{clearTimeout(t);b.classList.remove("holding")};b.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0)return;b.classList.add("holding");t=setTimeout(async()=>{await taskRepository.delete(original.id);overlay.remove();await onSaved({deleted:true,taskId:original.id})},2000)};["pointerup","pointerleave","pointercancel"].forEach(x=>b.addEventListener(x,stop));b.oncontextmenu=e=>e.preventDefault()}
  async function save(){const task={id:editing?original.id:(crypto.randomUUID?.()||`task-${Date.now()}`),name:draft.name,category:draft.category,schedule:{type:draft.type,repeats:draft.type==="anytime"?false:draft.repeats,days:draft.type==="days"?draft.days:[],weeks:draft.type==="weeks"?draft.weeks:[],months:["months","days","weeks"].includes(draft.type)?draft.months:[],oneTimeKeys:draft.oneTimeKeys,dateRule:draft.type==="dates"?draft.dateRule:null},defaultAssignedIds:original?.defaultAssignedIds||[actor.id],visibility:original?.visibility||draft.visibility,createdById:original?.createdById||actor.id,createdAt:original?.createdAt||new Date().toISOString(),active:original?.active!==false};if(task.visibility==="private")task.defaultAssignedIds=[task.createdById];try{editing?await taskRepository.update(task):await taskRepository.add(task);overlay.remove();await onSaved({deleted:false,taskId:task.id})}catch(e){console.error(e);alert("The task was not saved. Check the connection and try again.")}}
  name();
 }
 return Object.freeze({open});
})();
