const ChoreyTaskCreator=(()=>{
 const {daysOfWeek,monthsOfYear,escapeHTML,dateKey}=ChoreyUtils,{taskRepository}=ChoreyRepositories,clone=v=>JSON.parse(JSON.stringify(v));
 async function open(actor,onSaved,existingTask=null){if(!actor)return;const editing=!!existingTask;if(editing&&!ChoreyTaskModel.canEditTask(actor,existingTask))return;const original=existingTask?clone(existingTask):null;const draft=original?{name:original.name,category:original.category,type:original.schedule.type,days:[...(original.schedule.days||[])],week:original.schedule.week??null,months:[...(original.schedule.months||[])],date:original.schedule.date||null,seasonal:["days","weeks"].includes(original.schedule.type)&&!!original.schedule.months?.length,visibility:original.visibility}:{name:"",category:"General",type:null,days:[],week:null,months:[],date:null,seasonal:false,visibility:"visible"};
 const overlay=document.createElement("div");overlay.className="assignment-overlay";document.body.appendChild(overlay);const show=h=>overlay.innerHTML=`<div class="assignment-modal-card task-creator">${h}</div>`,cancel=()=>'<button class="modal-cancel" data-cancel>Cancel</button>',bind=()=>{overlay.querySelector("[data-cancel]")?.addEventListener("click",()=>overlay.remove());bindDelete()},sel=x=>x?" current-selection":"";
 function name(){show(`<div class="assignment-modal-title">${editing?"Edit Task":"New Task"}</div><form id="task-name-form"><label class="field-label">Name<input class="text-input" id="task-name" maxlength="80" value="${escapeHTML(draft.name)}" autofocus></label><button class="primary-button" type="submit">Continue</button></form>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#task-name-form").addEventListener("submit",e=>{e.preventDefault();draft.name=overlay.querySelector("#task-name").value.trim();if(!draft.name)return alert("Enter a task name.");category()})}
 async function categories(){const m=new Map(),add=v=>{v=String(v||"").trim();if(v&&!m.has(v.toLowerCase()))m.set(v.toLowerCase(),v)};defaultTasks.forEach(t=>add(t.category));(await taskRepository.getAll()).forEach(t=>add(t.category));return [...m.values()].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:"base"}))}
 async function category(){const list=await categories();show(`<div class="assignment-modal-title">Choose a category</div><ul class="chore-list category-selector-list">${list.map(c=>`<li class="chore-item selector-row${sel(c===draft.category)}" data-category="${escapeHTML(c)}"><span class="chore-title">${escapeHTML(c)}</span></li>`).join("")}<li class="chore-item selector-row" data-new-category><span class="chore-title">Add new category</span></li></ul>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll("[data-category]").forEach(r=>r.onclick=()=>{draft.category=r.dataset.category;visibility()});overlay.querySelector("[data-new-category]").onclick=newCategory}
 function newCategory(){show(`<div class="assignment-modal-title">New category</div><form id="category-form"><label class="field-label">Category name<input class="text-input" id="new-category" maxlength="40" autofocus></label><button class="primary-button" type="submit">Accept</button></form>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#category-form").onsubmit=async e=>{e.preventDefault();const c=overlay.querySelector("#new-category").value.trim();if(!c)return alert("Enter a category name.");draft.category=(await categories()).find(x=>x.localeCompare(c,undefined,{sensitivity:"base"})===0)||c;visibility()}}
 function visibility(){if(editing)return type();show(`<div class="assignment-modal-title">Who can see it?</div><ul class="chore-list"><li class="chore-item selector-row" data-vis="visible"><span class="chore-title">Household</span></li><li class="chore-item selector-row" data-vis="private"><span class="chore-title">Private 🔒</span></li></ul><p class="creator-note">Visibility is permanent. To change it later, delete and recreate the task.</p>${cancel()}`);bind();overlay.querySelectorAll("[data-vis]").forEach(r=>r.onclick=()=>{draft.visibility=r.dataset.vis;type()})}
 function type(){const choices=[["indefinite","Indefinite"],["once","Once"],["days","Days"],["weeks","Weeks"],["months","Months"]];show(`<div class="assignment-modal-title">How often?</div><ul class="chore-list">${choices.map(([v,l])=>`<li class="chore-item selector-row${sel(draft.type===v)}" data-type="${v}"><span class="chore-title">${l}</span></li>`).join("")}</ul>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll("[data-type]").forEach(r=>r.onclick=()=>{draft.type=r.dataset.type;if(draft.type==="indefinite")save();else if(draft.type==="once")date();else if(draft.type==="days")days();else if(draft.type==="weeks")week();else months(false)})}
 function date(){const now=ChoreyClock.now(),opts=[];for(let i=0;i<8;i++){const d=new Date(now);d.setDate(now.getDate()+i);opts.push({value:dateKey(d),label:i===0?"Today":i===1?"Tomorrow":i===7?`Next ${daysOfWeek[d.getDay()]}`:daysOfWeek[d.getDay()]})}show(`<div class="assignment-modal-title">Choose a day</div><ul class="chore-list">${opts.map(o=>`<li class="chore-item selector-row${sel(o.value===draft.date)}" data-date="${o.value}"><span class="chore-title">${o.label}</span></li>`).join("")}</ul>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll("[data-date]").forEach(r=>r.onclick=()=>{draft.date=r.dataset.date;save()})}
 function days(){show(`<div class="assignment-modal-title">Choose days</div><div class="selector-list">${daysOfWeek.map((d,i)=>`<label class="selector-check${sel(draft.days.includes(i))}"><input type="checkbox" value="${i}" ${draft.days.includes(i)?"checked":""}><span>${d}</span></label>`).join("")}<label class="selector-check seasonal-check"><input type="checkbox" id="seasonal" ${draft.seasonal?"checked":""}><span>Seasonal</span></label></div><button class="primary-button" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#accept").onclick=()=>{draft.days=[...overlay.querySelectorAll('.selector-check input:checked')].filter(i=>i.id!=="seasonal").map(i=>+i.value);draft.seasonal=overlay.querySelector("#seasonal").checked;if(!draft.days.length)return alert("Choose at least one day.");draft.seasonal?months(true):save()}}
 function week(){const opts=[[1,"First week"],[2,"Second week"],[3,"Third week"],[4,"Fourth week"],[5,"Fifth week"],["last","Last week"]];show(`<div class="assignment-modal-title">Choose a week</div><ul class="chore-list">${opts.map(([v,l])=>`<li class="chore-item selector-row${sel(String(v)===String(draft.week))}" data-week="${v}"><span class="chore-title">${l}</span></li>`).join("")}</ul><label class="selector-check seasonal-check"><input type="checkbox" id="seasonal" ${draft.seasonal?"checked":""}><span>Seasonal</span></label>${cancel()}${editing?del():""}`);bind();overlay.querySelectorAll("[data-week]").forEach(r=>r.onclick=()=>{draft.week=r.dataset.week==="last"?"last":+r.dataset.week;draft.seasonal=overlay.querySelector("#seasonal").checked;draft.seasonal?months(true):save()})}
 function months(seasonal){show(`<div class="assignment-modal-title">${seasonal?"Choose active months":"Choose months"}</div><div class="selector-list">${monthsOfYear.map((m,i)=>`<label class="selector-check${sel(draft.months.includes(i+1))}"><input type="checkbox" value="${i+1}" ${draft.months.includes(i+1)?"checked":""}><span>${m}</span></label>`).join("")}</div><button class="primary-button" id="accept">Accept</button>${cancel()}${editing?del():""}`);bind();overlay.querySelector("#accept").onclick=()=>{draft.months=[...overlay.querySelectorAll('input:checked')].map(i=>+i.value);if(!draft.months.length)return alert("Choose at least one month.");save()}}
 function del(){return '<button class="hold-delete-button" type="button" data-hold-delete><span class="hold-delete-progress"></span><span class="hold-delete-label">Hold to Permanently Delete</span></button>'}
 function bindDelete(){const b=overlay.querySelector("[data-hold-delete]");if(!b||!editing)return;let t;const stop=()=>{clearTimeout(t);b.classList.remove("holding")};b.onpointerdown=e=>{if(e.button!==undefined&&e.button!==0)return;b.classList.add("holding");t=setTimeout(async()=>{await taskRepository.delete(original.id);overlay.remove();await onSaved({deleted:true,taskId:original.id})},2000)};["pointerup","pointerleave","pointercancel"].forEach(x=>b.addEventListener(x,stop));b.oncontextmenu=e=>e.preventDefault()}
 async function save(){const task={id:editing?original.id:(crypto.randomUUID?.()||`task-${Date.now()}`),name:draft.name,category:draft.category,schedule:{type:draft.type,date:draft.type==="once"?draft.date:null,days:draft.type==="days"?draft.days:[],week:draft.type==="weeks"?draft.week:null,months:draft.type==="months"||draft.seasonal?draft.months:[]},defaultAssignedIds:original?.defaultAssignedIds||[],visibility:original?.visibility||draft.visibility,createdById:original?.createdById||actor.id,createdAt:original?.createdAt||new Date().toISOString(),active:original?.active!==false};if(task.visibility==="private")task.defaultAssignedIds=[];try{editing?await taskRepository.update(task):await taskRepository.add(task);overlay.remove();await onSaved({deleted:false,taskId:task.id})}catch(e){console.error(e);alert("The task was not saved. Check the connection and try again.")}}
 name();}
 return Object.freeze({open});
})();
