/* Calm, current-cycle interface. */
const ChoreyUI = (() => {
  const { getPerson, escapeHTML } = ChoreyUtils;
  const COLORS=["#3a9ad9","#8a63d2","#2bbbb0","#66cdaa","#e67e22","#d4af37","#cc6677","#6f9f4f","#5b8fd1","#b07cc6","#3aa6a0","#79b88a","#d99058","#c4a24d","#b85f6f","#7894c8","#9278bd","#4f9b94","#78a96c","#c98252"];
  const colorClaims=new Map();
  function categoryColor(category){
    const key=String(category||"General").trim().toLocaleLowerCase();
    if(colorClaims.has(key)) return colorClaims.get(key);
    let h=2166136261; for(const c of key){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}
    let index=(h>>>0)%COLORS.length; const used=new Set(colorClaims.values());
    for(let i=0;i<COLORS.length&&used.has(COLORS[index]);i++) index=(index+1)%COLORS.length;
    colorClaims.set(key,COLORS[index]); return COLORS[index];
  }
  function updateHeader(person,onAddTask,options={}){
    document.getElementById("day-heading").textContent=options.title||(person?"Today's Tasks":"Select Profile");
    const actions=document.getElementById("header-actions"),markup=person?'<button class="icon-button" id="add-task-button" aria-label="Add task">+</button>':"";
    if(actions.innerHTML!==markup) actions.innerHTML=markup;
    const add=document.getElementById("add-task-button");if(add) add.onclick=onAddTask;
  }
  function renderLoginScreen(onSelectProfile){const v=document.getElementById("app-viewport");v.innerHTML=`<ul class="chore-list">${people.map(p=>`<li class="chore-item profile-card" data-person-id="${p.id}" style="--person-accent:${p.accent}"><span class="chore-title profile-name">${escapeHTML(p.name)}</span></li>`).join("")}</ul>`;v.querySelectorAll("[data-person-id]").forEach(x=>x.onclick=()=>onSelectProfile(x.dataset.personId));}
  function canShowAssignment(item,active){if(!active||item.task.visibility==="private"||item.isDone)return false;if(ChoreyTaskModel.canManageAssignments(active))return true;return !item.assignedIds.length||item.selfAssignedIds?.includes(active.id);}
  function assignmentControl(item,active){if(!canShowAssignment(item,active))return item.task.visibility==="private"?'<span class="privacy-lock" aria-label="Private task">🔒</span>':"";const assigned=item.assignedIds.map(getPerson).filter(Boolean);const accent=assigned.length===1?assigned[0].accent:"";const cls=assigned.length?" is-assigned":"";const style=accent?` style="--assignee-accent:${accent}"`:"";const label=assigned.length?`Assigned to ${assigned.map(p=>p.name).join(", ")}`:"Assign task";return `<button class="assignment-button${cls}" type="button" aria-label="${escapeHTML(label)}"${style}><svg class="assignment-icon" viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.25"></circle><path d="M5.75 19c.45-3.45 2.55-5.25 6.25-5.25s5.8 1.8 6.25 5.25"></path></svg>${assigned.length>1?`<span class="shared-count">${assigned.length}</span>`:""}</button>`;}
  function renderTaskRow(item,active){const canEdit=ChoreyTaskModel.canEditTask(active,item.task);const card=`<div class="chore-item ${item.isDone?"completed-row":""}" data-id="${escapeHTML(item.id)}" style="--category-accent:${categoryColor(item.task.category)}"><input type="checkbox" class="chore-checkbox" ${item.isDone?"checked":""} tabindex="-1"><div class="chore-text-target"><span class="chore-title">${escapeHTML(item.displayTask)}</span></div>${assignmentControl(item,active)}</div>`;return canEdit?`<li class="swipe-row can-edit" data-task-id="${escapeHTML(item.task.id)}"><button class="swipe-action-button" type="button">Edit</button>${card}</li>`:`<li class="swipe-row">${card}</li>`;}
  const sort=(a,b)=>Number(a.isDone)-Number(b.isDone)||a.task.category.localeCompare(b.task.category,undefined,{sensitivity:"base"})||a.task.name.localeCompare(b.task.name,undefined,{sensitivity:"base"})||a.originalIndex-b.originalIndex;
  function dueLabel(now,close){const n=Math.max(0,Math.round((new Date(close+"T12:00:00")-new Date(now+"T12:00:00"))/86400000));return n===0?"Due: Today":n===1?"Due: Tomorrow":`Due: ${n} days`;}
  function renderSection(id,items,active,date,totalCount=items.length){const person=getPerson(id),title=person?`${person.name}'s Contributions`:"Unassigned Tasks";const by=d=>items.filter(i=>i.occurrence.duration===d).sort(sort);const groups=[["",by("day")],["Indefinite",by("indefinite")],["This Week",by("week")],["This Month",by("month")]];const content=groups.map(([label,list])=>list.length?`${label?`<li class="task-group-label"><span>${label}</span><span class="task-group-due">${["week","month"].includes(list[0].occurrence.duration)?dueLabel(date,list[0].occurrence.closesOn):""}</span></li>`:""}${list.map(i=>renderTaskRow(i,active)).join("")}`:"").join("")||'<li class="empty-state compact-empty">No tasks here.</li>';return `<div class="section-header ${person?"person-section":""}" ${person?`style="--person-accent:${person.accent}"`:""}><span>${escapeHTML(title)}</span><span class="section-count">${totalCount} ${totalCount===1?"item":"items"}</span></div><ul class="chore-list">${content}</ul>`;}
  function renderBoard(active,day,sections,options={}){const order=options.order||["unassigned",active.id,...people.filter(p=>p.id!==active.id).map(p=>p.id)];const counts=options.counts||new Map();const buttonLabel=options.buttonLabel||"Show Due Tasks";return order.map(id=>renderSection(id,sections.get(id)||[],active,day.dateKey,counts.has(id)?counts.get(id):(sections.get(id)||[]).length)).join("")+`<div class="owner-page-actions"><button class="secondary-button" id="view-mode-button">${escapeHTML(buttonLabel)}</button></div>`;}
  function taskGroup(t){if(t.schedule.type==="indefinite"||t.schedule.type==="once")return "once";if(t.schedule.type==="months"||(["days","weeks"].includes(t.schedule.type)&&t.schedule.months?.length))return "yearly";if(t.schedule.type==="weeks")return "monthly";return "daily";}
  function renderAllTasks(tasks,active){const groups={once:[],daily:[],monthly:[],yearly:[]};tasks.filter(t=>t.active!==false&&(t.visibility!=="private"||t.createdById===active.id)).forEach((t,i)=>groups[taskGroup(t)].push({task:t,index:i}));Object.values(groups).forEach(g=>g.sort((a,b)=>a.task.category.localeCompare(b.task.category)||a.index-b.index));const section=(key,title)=>`<div class="section-header"><span>${title}</span><span class="section-count">${groups[key].length} items</span></div><ul class="chore-list all-task-list">${groups[key].length?groups[key].map(({task})=>{const edit=ChoreyTaskModel.canEditTask(active,task);const row=`<div class="chore-item all-task-row" style="--category-accent:${categoryColor(task.category)}"><div class="chore-text-target"><span class="chore-title">${escapeHTML(task.category)}: ${escapeHTML(task.name)}</span></div>${task.visibility==="private"?'<span class="privacy-lock">🔒</span>':""}</div>`;return edit?`<li class="swipe-row can-edit" data-task-id="${task.id}"><button class="swipe-action-button">Edit</button>${row}</li>`:`<li class="swipe-row">${row}</li>`}).join(""):'<li class="empty-state compact-empty">No tasks here.</li>'}</ul>`;return section("once","Once / Indefinite")+section("daily","Daily")+section("monthly","Monthly")+section("yearly","Yearly")+'<div class="owner-page-actions"><button class="secondary-button" id="back-to-today">Back to Today</button></div>';}
  function emptyDayMarkup(buttonLabel="Show Due Tasks"){return `<ul class="chore-list"><li class="empty-state">All clear. No tasks are scheduled today.</li></ul><div class="owner-page-actions"><button class="secondary-button" id="view-mode-button">${escapeHTML(buttonLabel)}</button></div>`;}
  function renderEmptyDay(active){document.getElementById("app-viewport").innerHTML=emptyDayMarkup();}
  function showCongratulations(){const o=document.createElement("div");o.className="congrats-overlay";o.innerHTML="<h2>Today's Tasks Done</h2><p>Everything due today is checked off. Enjoy your day.</p>";document.body.appendChild(o);setTimeout(()=>{o.classList.add("fade-out");setTimeout(()=>o.remove(),400)},4600);}
  return Object.freeze({updateHeader,renderLoginScreen,renderBoard,renderAllTasks,renderEmptyDay,emptyDayMarkup,showCongratulations,categoryColor});
})();
