const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
const creator=fs.readFileSync('task-creator.js','utf8');
const css=fs.readFileSync('style.css','utf8');
assert(app.includes("assignmentSource='completion'"));
assert(app.includes("state.assignmentSource==='completion'"));
assert(app.includes("assignmentOverride:true"));
assert(app.includes("hold-assign-progress"));
assert(app.includes('await occurrenceRepository.resetAll()'));
assert(app.includes('ChoreyStorage.resetAllData()'));
assert(creator.includes('defaultAssignedIds:original?.defaultAssignedIds||[actor.id]'));
assert(creator.includes('task-name-input'));
assert(css.includes('@keyframes holdAssignFill'));
assert(css.includes('#task-name-form'));
assert(css.includes('gap: 14px'));
console.log('Interaction regression tests passed.');
